language: python
python:
    - "3.6"
install:
  - pip install scipy
  - pip install numba
  - pip install matplotlib
  - pip install scikit-learn
  - pip install spectral
  - pip install pytest 
  - pip install pep8
script:
  - pytest
